# Generated by Django 5.2.8 on 2025-11-21 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=233)),
                ('desc', models.TextField()),
                ('price', models.PositiveSmallIntegerField()),
                ('image', models.FileField(upload_to='product')),
            ],
        ),
    ]
